"""projects

Revision ID: 45353e52f7c7
Revises: 
Create Date: 2022-02-20 21:08:36.190114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45353e52f7c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cruise',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ecopartproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecotaxaproject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('ship',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('sample',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('ecopart_project_id', sa.Integer(), nullable=True),
    sa.Column('ecotaxa_project_id', sa.Integer(), nullable=True),
    sa.Column('profile_name', sa.String(), nullable=True),
    sa.Column('ship_name', sa.String(), nullable=True),
    sa.Column('cruise_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cruise_name'], ['cruise.name'], ),
    sa.ForeignKeyConstraint(['ecopart_project_id'], ['ecopartproject.id'], ),
    sa.ForeignKeyConstraint(['ecotaxa_project_id'], ['ecotaxaproject.id'], ),
    sa.ForeignKeyConstraint(['profile_name'], ['profile.name'], ),
    sa.ForeignKeyConstraint(['ship_name'], ['ship.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    op.drop_table('ship')
    op.drop_table('profile')
    op.drop_table('ecotaxaproject')
    op.drop_table('ecopartproject')
    op.drop_table('cruise')
    # ### end Alembic commands ###
