name: push_backend_heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ecopart-demo-backend"
          heroku_email: "gilles.faucherand@gmail.com"
          appdir: "backend"
          usedocker: "true"
          docker_heroku_process_type: "web"
